### ISSUE TITLE
Missing web.config file

### ISSUE THREAD

**Issue by aarongustafson** [FilipNest/colouredsquares#2]
You can set up the web socket connection in it too. Here’s the Node template: https://a-k-apart.com/webconfigs/web.config.node.txt

**Comment by FilipNest** [comment]
Added one and ran a test azure instance over at https://coloured-squares-10k.azurewebsites.net/ to check everything worked. Needed to change the port it ran on as 80 was blocked somehow so went with process.env.port if it's there, enabled websockets and added a wss:// version of the websockets as it's being run with an https certificate.

It seems to work. Fingers crossed it works on the contest version too.

**Comment by molant** [comment]
@FilipNest just deployed the latest version. Can you take a look see if it works as expected?
http://coloured-squares-10kapart2016.azurewebsites.net/233-249-65

**Comment by FilipNest** [comment]
Looks like it yes! Thank you!
